In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt , yp in zip(y_true, y_predicted):
        total_error += abs(yt-yp)
    print("Total_error:" ,total_error)
    mae = total_error /len(y_true)
    print("mae:" ,mae)
    return mae

In [3]:
mae(y_true , y_predicted)

Total_error: 2.5
mae: 0.5


0.5

In [4]:
np.log([0.0000000000000000001])  # kabhi v log([0]) ya log([1]) nahi lenge hamesa nearest to 0  or 1lena h

array([-43.74911677])

In [5]:
epsilon = 1e-15  # 0.0000000000000001

In [6]:
y_predicted

array([1, 1, 0, 0, 1])

In [7]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [8]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_predicted_new = np.array(y_predicted_new)

In [17]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [18]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

17.2696280766844

In [21]:
def log_loss(y_true , y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [22]:
log_loss(y_true , y_predicted)

17.2696280766844